# Generated by Django 5.1.2 on 2025-07-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0002_user_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
