# Generated by Django 5.1.2 on 2025-07-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0003_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='rank_score',
            field=models.FloatField(default=0),
        ),
    ]
