# Generated by Django 5.1.2 on 2025-07-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0004_gamedata_rank_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='cs',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='damage',
        ),
    ]
