# Generated by Django 5.1.2 on 2025-07-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0005_remove_gamedata_cs_remove_gamedata_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='game_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='total_score',
            field=models.FloatField(default=100),
        ),
    ]
