# Generated by Django 5.1.2 on 2025-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0006_gamedata_game_score_gamedata_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='is_best_player',
            field=models.BooleanField(default=False),
        ),
    ]
