# Generated by Django 5.1.2 on 2025-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0007_gamedata_is_best_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='kda_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='placement',
            field=models.CharField(default='', max_length=10),
        ),
    ]
