# Generated by Django 5.1.2 on 2025-08-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0008_gamedata_ai_score_gamedata_cs_gamedata_damage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='game_score',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='is_best_player',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='rank_score',
        ),
    ]
