# Generated by Django 5.1.2 on 2025-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0009_remove_gamedata_game_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='rank',
            field=models.CharField(default='', max_length=10),
        ),
    ]
