# Generated by Django 5.1.2 on 2025-08-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0010_gamedata_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
