# Generated by Django 5.1.2 on 2025-09-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0011_gamedata_title'),
    ]

    operations = [
    ]
