# Generated by Django 5.1.2 on 2025-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0012_auto_20250910_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='lp_after',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='lp_before',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='lp_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lp',
            field=models.IntegerField(db_index=True, default=150),
        ),
    ]
