# Generated by Django 5.1.2 on 2025-09-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapp', '0013_gamedata_lp_after_gamedata_lp_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lp',
        ),
    ]
